services:

  backend:
    build: .
    container_name: levelup_backend
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      APP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: thebuddha
      DB_NAME: levelup_hub
      REDIS_ADDR: redis:6379

    depends_on:
      - postgres
      - redis

    restart: always


  frontend:
    build: ../LevelUp_Hub_Frontend
    container_name: levelup_frontend
    ports:
      - "3000:3000"

    depends_on:
      - backend

    restart: always


  postgres:
    image: postgres:15-alpine
    container_name: levelup_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thebuddha
      POSTGRES_DB: levelup_hub

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    restart: always


  redis:
    image: redis:7-alpine
    container_name: levelup_redis

    ports:
      - "6379:6379"

    restart: always


volumes:
  postgres_data: